README.md
ssh git cloning will trigger an error
=> Use https instead of ssh

README.md, gradio_app.py, requirements_gradio.txt, test_infer_single.py
Hi,
Thanks for releasing F5-TTS!
This PR adds a Gradio app & MPS support for non-batched inference.
Thanks!
=> Add Gradio app, MPS support

inference-cli.py, inference-cli.toml, requirements.txt
I modified gradio_app.py and created a cli for batch inferencing.
Either you can specify everything in inference-cli.toml or override with flags like --model, --reference, --text.. when running inference-cli.py.
```toml
model = "F5-TTS"
reference = "tests/ref_audio/test_en_1_ref_short.wav"
subtitle = "Some call me nature, others call me mother nature."
text = "I don't really care what you call me. I've been a silent spectator, watching species evolve, empires rise and fall. But always remember, I am mighty and enduring. Respect me and I'll nurture you; ignore me and you shall face the consequences."
remove_silence = true
output_dir = "tests"
```
=> Command Line Interface for Inference

inference-cli.py
Sorry, I missed a bug that kept output from saved when remove_silence was false.
=> Fixed not saving output file when remove_silence is false.

gradio_app.py
I added a new "Emotional Text-to-Speech Generation" feature to the Gradio app, which lets users upload different audio clips for various speech styles.
The feature includes options to dynamically add and remove custom speech types. For example, users can upload reference audios for emotions like Regular, Whisper, Scream, Angry, Sad, Surprised, and more. Each type includes a reference audio, text input, and a delete option for easy management. You can also add new speech types using the "Add Speech Type" button.
To ensure smooth functionality, I implemented input validation that disables the "Generate Emotional Speech" button if the text contains emotions not defined by the user. The input text format looks like (Emotion) Text, and the system will generate speech based on the audio …
=> Added multiple speech types generation

gradio_app.py
This doesn't seem to work all the time, but that might be on the model.
Just added a slider to change to global set speed (default stays at 1.0)
=> Speed slider in gradio app

gradio_app.py
Hi,
This PR reorganizes the Gradio app, by moving the separate features into tabs.
Thanks!
=> Reorganize Gradio app

.github/workflows/sync-hf.yaml
Hi,
This PR adds a GitHub Action that will automatically update the HF Space on each commit.
In order for this Action to work, please create a new GitHub Secret for the action [here](https://github.com/SWivid/F5-TTS/settings/secrets/actions/new) called `REFRESH_PASSWORD`. I've invited you to a HF Org that contains the password, please set the value of that Secret to the password in the Org.
Thanks!
=> Sync to Hugging Face Space

gradio_app.py
In the Pinokio discord, user @jeffstunes developed a new batching method which, after lots of testing, seems better at maintaining proper flow at long audio generations. 
I also added the funcionality to make sure reference text ends in ". ", since after lots of testing, it seems much better this way.
=> Improved batching and added reference text ending

gradio_app.py
Added audio crossfading with configurable duration in Advanced Settings. Only available in Batched TTS.
Removed SPLIT_WORDS since it's no longer necessary.
Set default value of Remove Silences to false in Batched TTS due to being unnecessary in testing. (Could be substituted with better logic, if silence > x ms, splice and crossfade)
=> Added audio crossfading

README.md
Hi,
Thanks for releasing F5-TTS! This PR clarifies the licenses of the pre-trained models.
Thanks!
=> Clarify model licenses

scripts/prepare_csv_wavs.py
see here https://github.com/SWivid/F5-TTS/discussions/57#discussioncomment-10959029
=> add csv wavs data prep script

finetune-cli.py, finetune_gradio.py
Hi @SWivid  , I created a Gradio interface for fine-tuning. 
There's only one part I need to change in the training settings. Are there any good default settings I can use?
Tab transcribe 
a) You can simply place audio files in data/project_name/dataset . in tab transcribe check user**
```
my_speak/
│
├── dataset/
│   ├── audio1.wav
└── audio2.wav
```
b) Or you can just upload audio files directly in Gradio. In the Transcribe tab, uncheck the "user" option.
Tab preparing data
You can preparing data in second tab : You can place audio files in data/project_name/wavs and include a metadata.csv file. If you complete             the first step, there's no need to place anything else because the transcription will be created automatically.
```
my_speak/
│
├── wavs/
│   ├── audio1.wav
│   └── …
```
=> gradio_finetune

gradio_app.py
Increased the number of speech types since there's no reason to limit them.
=> Increase number of speech types.

finetune_gradio.py
just small update fix one small line in sample
=> fix max_sample

api.py, model/utils_infer.py
=> small fix in api remove_silence 

finetune_gradio.py
i just fix empty value when i delete need be **tts_api = None**
=> very quick fix in gradio_finetune.py

gradio_app.py
Changed multi-speechtype token to "{","}" from "(",")"
Fixed multi-speechtype UI and refined code
=> Fixed multi-speech-type and changed token to {}

finetune-cli.py, finetune_gradio.py
hi @SWivid  i just make a lot update in gradio add title and link here https://github.com/SWivid/F5-TTS/discussions/143
in create you can select **z** **pinyin** or **char**
when now create new project you can see easy in list and you can select form here
2) in train data you can change your Tokenizer  path and pretrain model
for this i add in finetune-cli.py new value **--pretrain** 
make better auto config (can you please check the part with epochs i think something wrong in line 612 - 629 )
i get from **count_max_epoch.py** i get 133225 epochs? this correct to calcuale the epochs ?
3) now in resude you can save also safetensors 
4 in test model now you can easy select checkpoint for combo list when you select the project up automatic find checkpoints
and also you can see device you use …
=> update gradio make more easy and automatic 

model/utils_infer.py
Added audio caching in utils_infer so if the same audio is used twice, it will not be transcribed again.
=> Added audio caching for faster inference

gradio_app.py
This will speed up loading times and optimize memory usage for users who don't want to use that feature
=> Added a Load button for the chat tab

finetune-cli.py, finetune_gradio.py
@SWivid  just another great update and fix some stuf 
first add create vocan from the dataset and you can see
support now calculate settng multi gpu in train find all gpu memory
add system info see cpu and gpu 
**question** 
can you please tell me only one part need fix in caluclate epochs 
from example see this 
i use 5 min 38 sample i get epoch **133235** ! this correct 
samples : 38  small i know 
```
total_hours = 0.0833
mel_hop_length = 256
mel_sampling_rate = 24000
wanted_max_updates = 1000000
gpus =1
frames_per_gpu = 3200
grad_accum = 1
```
=> new update gradio finetune

finetune_gradio.py
@SWivid something i miss 
here also video action all working great 
https://github.com/user-attachments/assets/ebf25212-2cc5-4570-b5ff-41b63a6f0f96
BTW: when you have free time please test
=> quick fix device always cpu !

src/f5_tts/train/finetune_gradio.py
@SWivid hi i fix path to work with last update
=> fix path finetune gradio

src/f5_tts/train/finetune_cli.py, src/f5_tts/train/finetune_gradio.py
hi @SWivid i just forget to add also finetune-cli 
now all working great again
=> fix path in finetune-cli working with new update 

src/f5_tts/train/finetune_cli.py, src/f5_tts/train/finetune_gradio.py
@SWivid This is just a small update for the last per step. I've added a note to change some values manually; so don't get confused some one. also change order tab and add note in vocab tab , and reduse checkpoint tab . i think now all clear and in correct order ,
=> gradio finetune fix last per step and add note

src/f5_tts/train/finetune_gradio.py
@SWivid ok i add use_ema by default it's **true**  and fix problem with leave empty space
=> add use_ema in model test for finetune gradio

src/f5_tts/train/finetune_cli.py, src/f5_tts/train/finetune_gradio.py
@SWivid just note for ema
ok i done for today i make a lot update now i think with have eveything ;)
=> finetune quick note for ema

src/f5_tts/train/finetune_cli.py, src/f5_tts/train/finetune_gradio.py
@SWivid just small update fix wrong value in setting
=> gradio finetune fix wrong value 

src/f5_tts/train/finetune_cli.py, src/f5_tts/train/finetune_gradio.py
@SWivid if you check **stream output** you can see the train in gradio !
not need change window to see in console i test and working  great i make defualt True , and also write note it's experiment
for any problem uncheck 
here review 
and i add refresh button to ignore problem with setting load
=> gradio stream output !

src/f5_tts/train/finetune_cli.py, src/f5_tts/train/finetune_gradio.py
@SWivid quick fix take vocab from the project when you extend the model  get error becuase always take emilia before, 
now take vocab for the project you working
=> finetune quick fix for the vocab take the vocab from the project

src/f5_tts/infer/infer_gradio.py
Added a text chat function that can be used alongside the microphone. It doesn't interfere with current functionality, it's just an optional extra way of interacting with the chat.
FYI: I've never made a pull request before, and I also used AI, so please review thoroughly.
Pre-commit passes and I've tried to check different ways it can be used, it all works fine for me. Hopefully this is useful to someone even if it isn't merged.
=> Add text chat function

src/f5_tts/model/trainer.py, src/f5_tts/model/utils.py, src/f5_tts/train/finetune_cli.py, src/f5_tts/train/finetune_gradio.py
@SWivid hi i add sample export and tensorboard 
when you call finetune-cli with `--export_samples` you exprot audio and mel 
when you call finetune-cli with `--logger` choices=["none", "wandb", "tensorboard"]
by defualt its `wandb` dont broken stuff 
here also new gradio finetune gui ;)
please check my code in trainer if all ok 
thank you
=> add tensorboard and add export sample for mel and audio 

src/f5_tts/train/finetune_gradio.py
@SWivid just quick update to suport format all case in metadata.csv
```
audio|text
audio.wav|text
full_path/audio.wav|text
```
=> gradio quick update suport for create metadata

src/f5_tts/api.py, src/f5_tts/train/finetune_gradio.py
@SWivid  in gradio when api_tts is None must load the model
in api with ref_text it's empty automatic transcribing
=> small fix stuff

.gitmodules, README.md, src/f5_tts/api.py, src/f5_tts/eval/eval_infer_batch.py, src/f5_tts/eval/utils_eval.py, src/f5_tts/infer/README.md, src/f5_tts/infer/infer_cli.py, src/f5_tts/infer/speech_edit.py, src/f5_tts/infer/utils_infer.py, src/f5_tts/model/cfm.py, src/f5_tts/model/dataset.py, src/f5_tts/model/modules.py, src/f5_tts/model/trainer.py, src/f5_tts/train/train.py
Support Bigvgan vocoder and update new version checkpoint with lower wer.
If I have checked this pr, I will merge and please help me check this code.
=> [WIP]Support Bigvgan vocoder

src/f5_tts/train/datasets/prepare_csv_wavs.py, src/f5_tts/train/finetune_gradio.py
@SWivid just small fix stuff 
so now when audio stereo always get duraction mono and resample
after train take case stereo to mono and resample
and just fix error speling the bf16
=> small update gradio finetune

src/f5_tts/infer/README.md, src/f5_tts/socket.py
- [add] socket server
- [edit] readme inference to use socket in stream
=> [add] socket stream

src/f5_tts/infer/utils_infer.py
@SWivid I’m sending you a fix for the problem to resolve glitch effect noise.
This removes the audio's silence at the start and end, and then adds 50 milliseconds of silence at the end. like this it's not create this glitch effect noise .
before
after
=> Fix the glitch effect at the beginning audio

src/f5_tts/infer/utils_infer.py
As per https://github.com/SWivid/F5-TTS/issues/443
=> Set PYTORCH_ENABLE_MPS_FALLBACK=1 for MPS by default

src/f5_tts/train/finetune_gradio.py
Wotking fix for path issues described in #480 (tested). Suggested solution before issue was closed did not correctly address the problems.
=> Fixes both issues from #480

src/f5_tts/infer/examples/basic/basic.toml, src/f5_tts/infer/infer_cli.py
I also noticed a an issue in the help text for --gen_file. so fixed that too.
=> Add output filename parameter to infer_cli. Closes #519

src/f5_tts/infer/SHARED.md
Here is my first finnish model at hugging face.
=> Finnish Model added at Hugging Face

src/f5_tts/infer/SHARED.md
=> Added Italian model card

src/f5_tts/infer/SHARED.md
Updated JA model after training for about 4 weeks on the same dataset.
=> Add updated JA model

src/f5_tts/model/trainer.py
when the model trained 50000 steps and saved the log_sample encountered error; the model_last.ckpt is 45000 ckpt.
If resuming the train, it will start at 45000, not 50000.
=> fix save last ckpt

src/f5_tts/infer/README.md
as the diff shows, the relative path file path is wrong, github will show 404
=> fix the SHARED.md file path

src/f5_tts/infer/infer_gradio.py
1. add model name input Textbox, just copy and paste the model name should work.
2. reload the model if the chat_model_state is not None
screenshot:
=> feature: support custom chat model

src/f5_tts/runtime/triton_trtllm/Dockerfile.server, src/f5_tts/runtime/triton_trtllm/README.md, src/f5_tts/runtime/triton_trtllm/client_grpc.py, src/f5_tts/runtime/triton_trtllm/client_http.py, src/f5_tts/runtime/triton_trtllm/docker-compose.yml, src/f5_tts/runtime/triton_trtllm/fill_template.py, src/f5_tts/runtime/triton_trtllm/model_repo_f5_tts/f5_tts/1/f5_tts_trtllm.py, src/f5_tts/runtime/triton_trtllm/model_repo_f5_tts/f5_tts/1/model.py, src/f5_tts/runtime/triton_trtllm/model_repo_f5_tts/f5_tts/config.pbtxt, src/f5_tts/runtime/triton_trtllm/model_repo_f5_tts/vocoder/config.pbtxt, src/f5_tts/runtime/triton_trtllm/patch/__init__.py, src/f5_tts/runtime/triton_trtllm/patch/f5tts/model.py, src/f5_tts/runtime/triton_trtllm/patch/f5tts/modules.py, src/f5_tts/runtime/triton_trtllm/run.sh, src/f5_tts/runtime/triton_trtllm/scripts/conv_stft.py, src/f5_tts/runtime/triton_trtllm/scripts/convert_checkpoint.py, src/f5_tts/runtime/triton_trtllm/scripts/export_vocoder_to_onnx.py, src/f5_tts/runtime/triton_trtllm/scripts/export_vocos_trt.sh, src/f5_tts/runtime/triton_trtllm/scripts/fill_template.py
This PR supports to serve F5-TTS using Nvidia TensorRT-LLM and Triton, enabling efficient and high-performance text-to-speech inference.
Thanks for the initial TRT-LLM DiT support in https://github.com/SWivid/F5-TTS/issues/588.
```sh
MODEL=F5TTS_Base docker compose up
python3 client_http.py
```
Decoding on a single L20 GPU, using 26 different prompt_audio/target_text [pairs](https://huggingface.co/datasets/yuekai/seed_tts_cosy2).
| Model | Concurrency | Avg Latency     | RTF | 
|-------|-------------|-----------------|--|
| F5-TTS Base (Vocos) | 1     | 253 ms | 0.0394|
=> Support GPU Depolyment Solution with Triton and TensorRT-LLM

src/f5_tts/runtime/triton_trtllm/README.md, src/f5_tts/runtime/triton_trtllm/benchmark.py, src/f5_tts/runtime/triton_trtllm/requirements-pytorch.txt, src/f5_tts/runtime/triton_trtllm/run.sh
The PR enables TRT-LLM inference in a single file, eliminating the dependency on Nvidia Triton.
Decoding on a single L20 GPU, using 26 different prompt_audio/target_text pairs.
| Model | Concurrency | RTF   | Mode |
|-------|--------------------------|-------|------|
| F5-TTS Base (Vocos) | 1 (Batch_size)       | 0.0402|Offline TRT-LLM|
| F5-TTS Base (Vocos) | 1 (Batch_size)     | 0.1467|Offline Pytorch|
=> [TRT-LLM] add benchmark code

src/f5_tts/train/datasets/prepare_emilia_v2.py
Hi,
This PR adds support for the new format of the Emilia dataset.
Thanks!
=> Add processing script for new Emilia dataset format

src/f5_tts/infer/infer_gradio.py
Hey,
I think some recent changes might have broken the Gradio app - this PR attempts to fix it.
Thanks!
=> Fix Gradio app
