SWivid/F5-TTS

gradio_app.py

Here's what the Batch Inference part does:
- Try to put as much characters as possible into one batch (200 max)
- If it's not possible, it'll try to do a cut whenever there's a semicolon character
- If it's not possible, it'll try to do a cut whenever there's a comma character
- If it's not possible, it'll try to do a cut after the most logical word (thus, therefore etc.) --> There's a list at the top of the Gradio script, and it's possible to modify it in Advanced Settings
- If nothing above worked, it's just going to go past that 200 line (realistically, if your text isn't gibberish, this shouldn't happen :D)
The Podcast Generation feature has these features built in:
- Takes two reference speeches and two reference texts (or empty and then transcribed automatically)
- You have to give …

Batch Inference & Podcast Generation

---

inference-cli.py
inference-cli.toml

Using -f option in cli, you can specify a file to read text to generate.
When both -t and -f are specified, -t is ignored.

Added -f option to read text from a file.

---

model/dataset.py
model/utils.py
train.py

Current path finding for tokenizer and dataset requires specific naming conventions to be found.  This open up new "custom" options that can be used to specify a tokenizer to use and a new dataset_type that allows you to pass the directory of a preprocessed directory without needing the name of the tokenizer in it.

Update to make passing in custom paths easier for finetuning/training

---

model/trainer.py
model/utils.py
scripts/eval_infer_batch.py
speech_edit.py

Given that people may be sharing around models, weights_only=True may be a safer way to ensure only weights are loaded as it is not a default torch option yet.

default to weights_only=True for safer loading

---

finetune_gradio.py

The existing finetune UI only lets you upload one audio clip file because it uses a gradio audio component (which only allows one file).
I switched it to use gradio file component with `file_count="multiple"` so we can upload multiple audio files and transcribe them all automatically.
Here's what it looks like:

allow multiple audio files for finetune UI

---

README.md
inference-cli.py

Hi, I created this update because I've noticed that many people here don't know how to change the model they want to load. Also, it's currently limited because the inference-cli.py script only loads the original model and vocabulary.
I've added a new argument to make it easier to use.
```
--vocab_file if empty take original 
--ckpt_file if empty take the original model
```
```bash
python inference-cli.py \
--model "F5-TTS" \
--ref_audio "tests/ref_audio/test_en_1_ref_short.wav" \
--ref_text "Some call me nature, others call me mother nature." \
--gen_text "I don't really care what you call me. I've been a silent spectator, watching species evolve, empires rise and fall. But always remember, I am mighty and enduring. Respect me and I'll nurture you; ignore me and you shall face the …
```

add new args in interface-cli.py for pass model and vocab

---

README.md
model/trainer.py

Two things to make the wandb integration more user friendly.
Currently the training script cannot be run unless you are already logged into wandb using something like `wandb login`. This means you have to run the login manually, and makes this not easily deployable (both locally and to cloud services).
Fortunately, if you have `WANDB_API_KEY` set, you do NOT need to manually login to wandb. This becomes especially important when we're trying to run this through the gradio UI, since we can no longer assume the user is running things manually from the terminal. There needs to be a way for the gradio app to launch without first having to run `wandb login` in the terminal. This PR documents this feature, so to use the logging (for both the cli and the gradio app), one just needs to set the …

User-friendly wandb support

---

api.py
model/utils_infer.py

hi @SWivid i create api  to easy use . and now you can use anywhere you like and simple call
only i notice something the cpu it's not working with last update **fp16** can you check it
i know the cpu for interface slow but from me it's immortal because when i do train and i want to check checkpoit i call infer with cpu to don't crash memory 
`from api import F5TTS`
```
f5tts=F5TTS()
wav,sr,spect=f5tts.infer(
ref_file="tests/ref_audio/test_en_1_ref_short.wav",
ref_text="Some call me nature, others call me mother nature.",
gen_text="""I don't really care what you call me.""",
file_wave="/home/F5-TTS/test.wav"
)
```
```
f5tts=F5TTS(
model_type="F5-TTS",
ckpt_file=r"/home/F5-TTS/ckpts/my_speak/model_1200000.pt", 
vocab_file=r"/home/F5-TTS/data/my_speak/vocab.txt",
ode_method="euler", …
```

add api for easy use 

---

README.md
gradio_app.py
requirements.txt

@SWivid This one I will not merge myself because I need your confirmation. This adds an AI Voice Chat feature using LLM Qwen2.5-3B (very fast), 3gb only, but needs pip install transformers_stream_generator. 
I hope you like it.
Also I added it to the README.md features section and to requirements.txt

Add Voice Chat feature

---

pyproject.toml

Specify required Gradio version to avoid errors with the Progress object. Earlier versions will give the error:
```
File ".../F5-TTS/model/utils_infer.py", line 268, in infer_batch_process
text_list = [ref_text + gen_text]
TypeError: can only concatenate str (not "Progress") to str
```
I am pretty sure the PR which changed this behavior is https://github.com/gradio-app/gradio/pull/5693, which was merged for 3.45.2. Certainly, you get the above error with 3.36.1 and it works with 3.45.2.

Update pyproject.toml - Specify required Gradio version

---

.github/workflows/publish-docker-image.yaml

This will build the dockerfile and create a github package that can be downloaded any time there's a push to 'main'.
Once this is in place and built, users can simply:
```
docker pull ghcr.io/SWivid/F5-TTS:main
```
Instead of building it themselves.

add dockerfile build

---

README.md

```bash
docker build -t f5tts:v1 .
docker pull ghcr.io/swivid/f5-tts:main
```
```bash
docker build -t f5tts:v1 .
docker pull ghcr.io/SWivid/F5-TTS:main
[+] Building 0.1s (1/1) FINISHED                                                                                                                                           docker:orbstack
=> [internal] load build definition from Dockerfile                                                                                                                                  0.0s
=> => transferring dockerfile: 2B                                                                                                                                                    0.0s
ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or …
```

Update README: must be lowercase docker

---

src/f5_tts/train/finetune_cli.py
src/f5_tts/train/finetune_gradio.py

@SWivid i replace the `utf-8-sig` to`utf-8` when i write the symbols becuase curse problem with space 
i think you need change here https://github.com/SWivid/F5-TTS/blob/1888fa49191b3c674db18dce3eb8c3bc58631e7c/src/f5_tts/model/utils.py#L125
because here you open like  `utf-8` 
if change to  `utf-8-sig` working but i dont want make this change first i want to ask you to curse something 
also i the **2546**  ""  it's just empty symbols , but like i see use in vocab ? , anyway i leave like this now 
to dont curse problem , now all must working fine i just test

in gradio finetune fix problem curse problem space in symbols

---

src/f5_tts/model/trainer.py

Fixed an issue where torchaudio.save was trying to save a CUDA tensor, causing a TypeError. The fix moves the gen_audio tensor to the CPU using .cpu() before calling torchaudio.save, ensuring compatibility with NumPy and torchaudio.

Ensure tensors are moved to CPU before saving with torchaudio

---

src/f5_tts/train/finetune_cli.py

Add `--bnb_optimizer` argument to CLI and pass it to Trainer initialization.
* Add `--bnb_optimizer` argument to `parse_args()` function in `src/f5_tts/train/finetune_cli.py`.
* Pass `bnb_optimizer` argument to `Trainer` initialization in the `main()` function of `src/f5_tts/train/finetune_cli.py`.

Add --bnb_optimizer argument to CLI and pass it to Trainer initialization

---

src/f5_tts/api.py
src/f5_tts/infer/SHARED.md
src/f5_tts/infer/utils_infer.py

Makes `local_path` more robust by downloading the models to path specified instead of needing to have the files already.

Allow for local path specification of HF models/repos

---

src/f5_tts/api.py
src/f5_tts/infer/utils_infer.py
src/f5_tts/train/finetune_cli.py
src/f5_tts/train/finetune_gradio.py

@SWivid hi i make some new fix update
and a add 8bit , and also i add in utlis infer new function for get easy transcripe 
also fix sime values

add in gradio finetune 8bit value fix some stuff and add new transcripe into easy  

---

src/f5_tts/socket_server.py

generate_stream() was processing the final chunk twice, causing it to repeat the last word.  I removed the redundancy, but needed to add logic to handle an edge case that would occur if the full audio chunk was smaller than the chunk size.  I'm not sure if such an edge case is even possible but I threw it in just in case.

Removed redundant final chunk logic from socket_server.py

---

src/f5_tts/infer/infer_gradio.py

Enables providing a reverse proxy subdirectory to gradio. Without this, trying to host the f5 gradio service behind the non-root path of a domain results in incorrect resource/asset paths.

Add root_path argument to support reverse proxies

---

src/f5_tts/model/cfm.py

In order to make `y0` take N steps from t = 0 to t = 1 in `torchdiffeq.odeint()` method, when initializing `t` using `torch.linspace(start, end, steps)`, the `steps` argument should be set to N + 1.

Fix sample timesteps

---

src/f5_tts/infer/utils_infer.py

Upwards directory traversal goes after getting the base path.
Tested on Linux, using F5-TTS and BigVGAN. Audio is generated.

utils_infer.py: Fix pathing issue that prevents importing BigVGAN

---

README.md

There have been some requests for support on AMD. So far it appears the suggestions have been to use other frame works that may work but would lead to less than ideal performance, uses windows only tech, or depends on libraries that are not ready for prime time.
https://github.com/SWivid/F5-TTS/issues/415
Using torch compiled for ROCm however does work for the limited subset of ROCm supported GPU's.
Tested and confirmed working on an AMD 7900XTX, Arch Linux

Provide instructions for AMD GPU

---

src/f5_tts/train/finetune_cli.py
src/f5_tts/train/finetune_gradio.py

I use f5-tts_finetune-gradio and found out that the finetune checkbox will always send finetune=true to the argument, eventhought the checkbox are off.
After some investigation turns out using type=bool on ArgumentParser always return true because in python:
`bool("False")` are `True`.

Bug Fix: Parsing Argument --finetune always True

---

README.md
src/f5_tts/api.py
src/f5_tts/eval/eval_utmos.py
src/f5_tts/infer/speech_edit.py
src/f5_tts/infer/utils_infer.py
src/f5_tts/socket_server.py
src/f5_tts/train/finetune_gradio.py

Support for Intel Gpus via pytorch+xpu
**Inference there was no problem**
Getting Started on Intel GPU
https://pytorch.org/docs/main/notes/get_start_xpu.html
`Intel® Deep Learning Essentials` or `Intel® oneAPI Base Toolkit` must be installed
Version 2025.0.1 has been verified
verify device:
Intel ARC A-Series A770 16G
Intel ARC A-Series A750
_The code may work equally well for Intel Extension for PyTorch(IPEX), but the environment is deployed differently_

Added intel XPU support

---

src/f5_tts/train/finetune_gradio.py

Robust settings loader to handle missing keys, incorrect file paths, and dynamic assignment
- Ensured default settings are properly merged with file-based settings to prevent KeyErrors.
- Added logic to handle `_pinyin` and `_char` suffixes in project names, ensuring correct file paths.
- Implemented tuple-based ordered mapping for consistent and error-free component assignment.
- Added safety check to verify the existence of `setting.json` before loading.
- Improved maintainability by centralizing default settings and enhancing error handling.
Bug Fixed!

Fix Settings Loader Issues: Resolve KeyErrors, Path Handling, and Component Assignment (#731)

---

src/f5_tts/infer/infer_gradio.py

Hi,
This PR adds a link back to the Gradio app and clarifies that the online demo is not running locally.
Thanks!

Add link back to GitHub repo, clarify local demo

---

src/f5_tts/infer/speech_edit.py
src/f5_tts/infer/utils_infer.py

cb8ce3306d70dfbee0e7d2423cc7f06e1c2b9c60
#477 
#475
Low - This is a simple typo fix in an environment variable name that affects MPS device compatibility.
Fixes a typo in the environment variable name `PYTOCH_ENABLE_MPS_FALLBACK` to `PYTORCH_ENABLE_MPS_FALLBACK` in two files:
- src/f5_tts/infer/speech_edit.py
- src/f5_tts/infer/utils_infer.py
Bug fixes (non-breaking change which fixes an issue)
Possibly:
```py
pip3 install torch torchvision torchaudio
```
Check the environment variable name correction in both files:
1. src/f5_tts/infer/speech_edit.py
2. src/f5_tts/infer/utils_infer.py
1. Test the code on an MPS-enabled device (e.g., Apple Silicon Mac) to verify that MPS fallback works correctly
2. Verify that the environment variable is properly recognized by PyTorch
The corrected …

fix: typo in MPS PyTorch env variable

---

README.md
src/f5_tts/infer/infer_gradio.py

N/A
Low - This is a simple addition of a command line flag for user convenience with no changes to core functionality.
Adds an `--autolaunch` / `-l` command line flag to automatically open the web interface in the default browser when starting the application.
Features (non-breaking change which adds functionality)
- Adds a new optional command line parameter
- Maintains backward compatibility with existing behavior
I have updated the documentation accordingly.
1. Review the changes in `src/f5_tts/infer/infer_gradio.py`
2. Test the new `--autolaunch` / `-l` flag functionality
1. Run the application without the flag to verify default behavior remains unchanged
2. Run the application with `--autolaunch` or `-l` flag and verify:
- Application starts normally
- Web interface automatically …

feat: Add autolaunch option to Gradio interface

---

src/f5_tts/infer/utils_infer.py

Use infer_cli.py, put in a really long prompt that needs  100+ batches.
ie. when someone wants to read an eBook.
It will gradually use up more and more VRAM.  These changes will make it so the VRAM usage stays the same.
I think it's because when you take a part of a tensor, it'll mark the tensor as being used even when you're not using it and you have to del it to free up the VRAM.
Related: https://github.com/niknah/ComfyUI-F5-TTS/issues/37

VRAM usage on long texts gradually uses up memory.

---

Dockerfile
README.md

Adding `VOLUME` to the Dockerfile gives a hint to users about which folders they probably want to mount to avoid excessive data fetching from the internet.
Adding `EXPOSE` to the Dockerfile gives a hint to users about which port they probably want to expose to access the web service under default configuration.
Adding a more complete `docker container run` command lets people quickly get started with the project with a single copyable command.
Adding the GUI run command gives a simple to use quickstart command for users that don't want to do a deep dive into understanding everything and they just want a GUI.
----
It may be worth moving the Docker quickstart command to the top of the Readme, as it is the fastest/easiest way to get things going, but I didn't want to make that big of a …

Improves documentation around docker usage.

---

src/f5_tts/infer/SHARED.md

update the Japanese hf path, the JA_25498980 was deleted, below is the latest path:
https://huggingface.co/Jmica/F5TTS/tree/main/JA_21999120

fix: update Japanese latest hf path

---

pyproject.toml

when start gradio got below error, based on [this issue](https://github.com/gradio-app/gradio/issues/10649#issuecomment-2675018488) use `pydantic==2.10.6` can solve the issue
```
if "const" in schema:
TypeError: argument of type 'bool' is not iterable
ERROR:    Exception in ASGI application
```

fix: use pydantic==2.10.6 to avoid bool is not iterable

---

src/f5_tts/infer/speech_edit.py

When I was trying to test `speech_edit.py`, I discovered the following error, which seems to point to a folder in the current repo. However, I see that `infer_gradio.py` and `infer_cli.py` both use cache paths, so I made modifications to it.
```
(f5-tts) ➜  F5-TTS git:(main) python src/f5_tts/infer/speech_edit.py
Download Vocos from huggingface charactr/vocos-mel-24khz
Traceback (most recent call last):
File "/Users/tbxark/Desktop/Repos/github/F5-TTS/src/f5_tts/infer/speech_edit.py", line 125, in <module>
model = load_checkpoint(model, ckpt_path, device, dtype=dtype, use_ema=use_ema)
File "/Users/tbxark/Desktop/Repos/github/F5-TTS/src/f5_tts/infer/utils_infer.py", line 200, in load_checkpoint
checkpoint = load_file(ckpt_path, device=device)
File …
```

chore: Update the model checkpoint path to use the cache path.

---

src/f5_tts/infer/SHARED.md

We fine-tuned a German model on the Mozilla Common Voice 19.0 dataset and around 800 hours of in the wild videos. The result can be found on huggingface: https://huggingface.co/hvoss-techfak/F5-TTS-German

German Model support

---

src/f5_tts/runtime/triton_trtllm/client_grpc.py

This PR aims to update the computation of metrics such as RTF by using `actual_duration` instead of the currently used estimated values.
Currently, in the codebase, `total_duration` is calculated based on an estimated target duration:
```python
estimated_target_duration = duration / len(reference_text) * len(target_text)
latency_data.append((end, estimated_target_duration))
total_duration += estimated_target_duration
rtf = elapsed / total_duration
```
This change will allow for more accurate metric calculation by relying on actual measured durations rather than estimations. When the length of target text is long enough, estimated durations and actual ones can differ significantly.

Fix the duration computation in `triton_trtllm/client_grpc.py`

---

src/f5_tts/model/backbones/dit.py
src/f5_tts/model/backbones/mmdit.py
src/f5_tts/model/backbones/unett.py
src/f5_tts/model/cfm.py
src/f5_tts/model/modules.py

With CFG, the DiT model forward twice, once with cond and once without.
However, the two forwards can be batched and computed together, which is exactly what this PR does.
This PR can nearly double the inference performance.

Speedup inference by batching CFG in DiT

---

pyproject.toml
src/f5_tts/infer/infer_cli.py

-   Added `unidecode` to `pyproject.toml` dependencies for ASCII text normalization 📚.
-   Modified `infer_cli.py` to use `unidecode` for WAV file names of audio chunks 🎵. Previously, raw `gen_text_` could include non-ASCII characters (e.g., "Téxt" → "Text", "こんにちは" → "konnichiha", or Vietnamese "Tiếng Việt" → "Tieng Viet"), risking file system errors 🚫. Now, `unidecode` ensures ASCII-compliant names, maintaining the format `index_unidecoded_text.wav`. This enhances cross-platform compatibility and prevents naming issues on systems with strict character restrictions 🌐.

Update WAV File Naming and Dependencies 📝🔊
